# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
executors:
  my-custom-executor:
    docker:
      - image: cimg/go:1.18.3
        auth:
          # ensure you have first added these secrets
          # visit app.circleci.com/settings/project/github/sixwaaaay/bytelite/environment-variables
          username: $DOCKER_HUB_USER
          password: $DOCKER_HUB_PASSWORD
jobs:
  my-job-test:

    executor: my-custom-executor
    steps:
      - checkout
      - run: |
          go mod tidy
          go test  -count=1 -coverprofile=cover-source.out   -p 1 -covermode=set -v ./... -coverpkg=./...

workflows:
  my-custom-workflow:
    jobs:
      - my-job-test