Host: 0.0.0.0
Port: 8888
DSN: root:123456@tcp(127.0.0.1:3306)/test?charset=utf8mb4&parseTime=True&loc=Local
Cache:
  - Host: localhost:6379

JWTSecret: jwt_secret

Minio:
  Endpoint: localhost:44444
  AccessKey: minio
  SecretKey: minio
  UseSSL: false
  Bucket: oss

ContentBaseUrl: http://localhost:9999/content